# Generated by Django 6.0.1 on 2026-01-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A descriptive title for the image', max_length=200)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Optional image description')),
                ('category', models.CharField(choices=[('nature', 'Nature'), ('architecture', 'Architecture'), ('people', 'People'), ('events', 'Events')], default='events', help_text='Category for filtering', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the image appears in the gallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
